import { Geist } from "next/font/google";
import { Poppins } from "next/font/google";
import "@/assets/styles/globals.css";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistSans.variable} antialiased`}
        suppressHydrationWarning
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
